### ISSUE TITLE
what is the application id for the windows

### ISSUE THREAD

**Issue by Litioblue** [MohsenHaydari/flutter_windows_notification#1]
Thank you very much for the package. Can you explain to me what is the **application id**? where do i find it in my project. 

```
// Create an instance of Windows Notification with your application name
// application id must be null in packaged mode
final _winNotifyPlugin = WindowsNotification(applicationId: "r"{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}\WindowsPowerShell\v1.0\powershell.exe"");
```

thanks

**Comment by mrtnetwork** [comment]
hi, the application user model ID (AUMID) is a unique id for each application in windows, if you want to use this package in package mode you must set null, but in debug, if you don't set the application id app will be crashed.
[microsoft](https://learn.microsoft.com/en-us/windows/win32/shell/appids)
if you want use [MSIX](https://pub.dev/packages/msix) to build your application you must following this [configuration ](https://github.com/YehudaKremer/msix/blob/main/doc/toast_notifications_configuration.md)

**Comment by aditya113141** [comment]
Thanks for suggesting, btw can anyone explain how to get the AUMID of my flutter application if it is not packaged. It is still in development phase and we run it by using `flutter run` on windows terminal

**Comment by mrtnetwork** [comment]
> Thanks for suggesting, btw can anyone explain how to get the AUMID of my flutter application if it is not packaged. It is still in development phase and we run it by using `flutter run` on windows terminal

open windows windows powershell (not command prompt) and use this command `Get-StartApps`

**Comment by randal923** [comment]
Thanks for explaining how to get the application ID. Please consider adding this to the documentation so other people can use the package.
