### ISSUE TITLE
Notifications are sent without app logo

### ISSUE THREAD

**Issue by untitledappseu** [MohsenHaydari/flutter_windows_notification#14]
Please fix this

**Comment by untitledappseu** [comment]
@mrtnetwork

**Comment by mrtnetwork** [comment]
> @mrtnetwork

Hey, the app logo will only show in release mode, or ensure you've set the correct application ID.

**Comment by untitledappseu** [comment]
I see. They weren't showing up in Testing. Thanks for the fast response!
