### ISSUE TITLE
maximize app when click notification

### ISSUE THREAD

**Issue by anvers** [MohsenHaydari/flutter_windows_notification#15]
Hi, i want to know if existe ahi param or method for open the app when click the notification. 

This is my part of code for windows_notification: 

        NotificationMessage messagePopup = NotificationMessage.fromPluginTemplate(
          "Alarga Error Job",
          "Nombr de job: $message",
          "Error: $cuerpo",
        );
        _winNotifyPlugin.showNotificationPluginTemplate(messagePopup);

thanks!

**Comment by mrtnetwork** [comment]
> Hi, i want to know if existe ahi param or method for open the app when click the notification.
> 
> This is my part of code for windows_notification:
> 
> ```
>     NotificationMessage messagePopup = NotificationMessage.fromPluginTemplate(
>       "Alarga Error Job",
>       "Nombr de job: $message",
>       "Error: $cuerpo",
>     );
>     _winNotifyPlugin.showNotificationPluginTemplate(messagePopup);
> ```
> 
> thanks!

hi, you must use Launch property with your app deeplink uri.

**Comment by anvers** [comment]
> > Hi, i want to know if existe ahi param or method for open the app when click the notification.
> > This is my part of code for windows_notification:
> > ```
> >     NotificationMessage messagePopup = NotificationMessage.fromPluginTemplate(
> >       "Alarga Error Job",
> >       "Nombr de job: $message",
> >       "Error: $cuerpo",
> >     );
> >     _winNotifyPlugin.showNotificationPluginTemplate(messagePopup);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thanks!
> 
> hi, you must use Launch property with your app deeplink uri.

Hi @mrtnetwork , deeplink uri not is only for mobile pplataform?

**Comment by mrtnetwork** [comment]
i mean

> > > Hi, i want to know if existe ahi param or method for open the app when click the notification.
> > > This is my part of code for windows_notification:
> > > ```
> > >     NotificationMessage messagePopup = NotificationMessage.fromPluginTemplate(
> > >       "Alarga Error Job",
> > >       "Nombr de job: $message",
> > >       "Error: $cuerpo",
> > >     );
> > >     _winNotifyPlugin.showNotificationPluginTemplate(messagePopup);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > thanks!
> > 
> > 
> > hi, you must use Launch property with your app deeplink uri.
> 
> Hi @mrtnetwork , deeplink uri not is only for mobile pplataform?


Maybe I am using the wrong name to explain it, take a look at this package, it worked for me [applink](https://pub.dev/packages/app_links)

**Comment by anvers** [comment]
> i mean
> 
> > > > Hi, i want to know if existe ahi param or method for open the app when click the notification.
> > > > This is my part of code for windows_notification:
> > > > ```
> > > >     NotificationMessage messagePopup = NotificationMessage.fromPluginTemplate(
> > > >       "Alarga Error Job",
> > > >       "Nombr de job: $message",
> > > >       "Error: $cuerpo",
> > > >     );
> > > >     _winNotifyPlugin.showNotificationPluginTemplate(messagePopup);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > thanks!
> > > 
> > > 
> > > hi, you must use Launch property with your app deeplink uri.
> > 
> > 
> > Hi @mrtnetwork , deeplink uri not is only for mobile pplataform?
> 
> Maybe I am using the wrong name to explain it, take a look at this package, it worked for me [applink](https://pub.dev/packages/app_links)

Thanks for the reply @mrtnetwork .When i use this package and configure the launch params, this open another app. So for new notification and make click, open a app instance. THis is correct  ? or i doing something wrong? 
Thaks!

**Comment by mrtnetwork** [comment]
I'm closing this issue. If you have any further questions or concerns, please don't hesitate to reach out
