### ISSUE TITLE
Release build works perfectly on local Windows machine but fails on CI (GitHub Actions, runs-on: windows-latest)

### ISSUE THREAD

**Issue by JanZeman** [MohsenHaydari/flutter_windows_notification#16]
Hello,

Thank you for a very nice plugin! I basically need just a simple text-based notification on Windows but will gladly experiment with more advanced ones later :)

I have however one relatively big obstacle. While my local build works perfectly for `flutter build windows --release` , the CI build started to fail after I added your plugin. It is some kind of conversion error. I will try to investigate bit more on my own but if you knew right away what the root cause might be the fix or at least hint would be highly appreciated.

Many regards, Jan

`jobs:
  build:
    runs-on: windows-latest`

`windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: 'std::string winrt::to_string(std::wstring_view)': cannot convert argument 1 from 'winrt::com_ptr<To>' to 'std::wstring_view' [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
Building Windows application...                                 
windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664:         with [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664:         [ [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664:             To=winrt::hstring [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664:         ] [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
Building Windows application...                                   288.2s
Build process failed.`

**Comment by mrtnetwork** [comment]
> Hello,
> 
> Thank you for a very nice plugin! I basically need just a simple text-based notification on Windows but will gladly experiment with more advanced ones later :)
> 
> I have however one relatively big obstacle. While my local build works perfectly for `flutter build windows --release` , the CI build started to fail after I added your plugin. It is some kind of conversion error. I will try to investigate bit more on my own but if you knew right away what the root cause might be the fix or at least hint would be highly appreciated.
> 
> Many regards, Jan
> 
> `jobs: build: runs-on: windows-latest`
> 
> `windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: 'std::string winrt::to_string(std::wstring_view)': cannot convert argument 1 from 'winrt::com_ptr<To>' to 'std::wstring_view' [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] Building Windows application... windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: with [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: [ [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: To=winrt::hstring [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: ] [build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] Building Windows application... 288.2s Build process failed.`

Hi, Thanks
I believe it's related to [issue](https://github.com/mrtnetwork/flutter_windows_notification/issues/11). I've updated the package on Pub Dev to version 1.1.0. Kindly update the package and inform me of any feedback or issues.

**Comment by JanZeman** [comment]
Hi @mrtnetwork , on the spot! 1.1.0 builds like a charm 👍 
I implemented some more logging into my CI build but it's not gonna be necessary anymore :)
Thank you so much for your immediate action!

Just as I wanted to press the enter, I tested the local build. Not sure yet what is happening but I get very often this crash:

![image](https://github.com/mrtnetwork/flutter_windows_notification/assets/1670470/04bf946e-7fcc-4197-9a4c-be19197516ce)

I did not observe it on 1.0.0 version, at least not that often as now. I started to experiment with your plugin just yesterday, so apologies for my not very structured feedback. I think this bug can be closed as I can build on CI by now the same way I can build locally. If I manage to prove a new bug sneaked in, I will create another ticket.

**Comment by mrtnetwork** [comment]
> Hi @mrtnetwork , on the spot! 1.1.0 builds like a charm 👍 I implemented some more logging into my CI build but it's not gonna be necessary anymore :) Thank you so much for your immediate action!
> 
> Just as I wanted to press the enter, I tested the local build. Not sure yet what is happening but I get very often this crash:
> 
> ![image](https://private-user-images.githubusercontent.com/1670470/320004811-04bf946e-7fcc-4197-9a4c-be19197516ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjM5OTksIm5iZiI6MTcxMjMyMzY5OSwicGF0aCI6Ii8xNjcwNDcwLzMyMDAwNDgxMS0wNGJmOTQ2ZS03ZmNjLTQxOTctOWE0Yy1iZTE5MTk3NTE2Y2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMTMyODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcyNmVlZTQwY2VjMzQ2MDc0MWJlNjJlMTViYTcyYzE0M2RiYzkzNjUxNmZlMGQ1ZGUxZDczZjM1ZWFmYjhmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X4q4qqjHvLFbTiF888i_fz2C4o6epzdnljoueKRPJDA)
> 
> I did not observe it on 1.0.0 version, at least not that often as now. I started to experiment with your plugin just yesterday, so apologies for my not very structured feedback. I think this bug can be closed as I can build on CI by now the same way I can build locally. If I manage to prove a new bug sneaked in, I will create another ticket.

For now, I don't have a Windows machine for building, but I remember that when I fixed this issue, I successfully built it on Windows. Then, I submitted the [pull request](https://github.com/mrtnetwork/flutter_windows_notification/pulls?q=is%3Apr+is%3Aclosed), tried cleaning the cache, and rebuilt it, resolving my issue.

**Comment by JanZeman** [comment]
I still experience the 'new' problem but closing this ticket as the CI problem is gone. I'll create a separated ticket if I find very good repro steps. Thanks again!
