### ISSUE TITLE
Clicking on <actions> does not respond

### ISSUE THREAD

**Issue by PeterCore** [MohsenHaydari/flutter_windows_notification#17]
<action
      activationType="system"
      arguments="snooze"
      hint-inputId="snoozeTime"
      content=""/>

    <action
      activationType="system"
      arguments="dismiss"
      content=""/>

**Comment by mrtnetwork** [comment]
> ```
> <action
>   activationType="system"
>   arguments="dismiss"
>   content=""/>
> ```

you should consult Microsoft's documentation for that. Many of these arguments provide actions in different statuses or require certain inputs. This plugin just sends the template to the notification service.

**Comment by mrtnetwork** [comment]
I'm closing this issue. If you have any further questions or concerns, please don't hesitate to reach out
