### ISSUE TITLE
The 'windows_notification' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel

### ISSUE THREAD

**Issue by bybabek** [MohsenHaydari/flutter_windows_notification#18]
[ERROR:flutter/shell/common/shell.cc(1038)] The 'windows_notification' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Comment by mrtnetwork** [comment]
> [ERROR:flutter/shell/common/shell.cc(1038)] The 'windows_notification' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel. See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

I've checked it once but couldn't resolve it. Since I didn't notice any performance issues, I postponed addressing it for later. I'll make sure to revisit it at a more opportune moment.

**Comment by heiha100** [comment]
It seems occur when app window was hide, and the app in tray mode

**Comment by mrtnetwork** [comment]
> It seems occur when app window was hide, and the app in tray mode

> [ERROR:flutter/shell/common/shell.cc(1038)] The 'windows_notification' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel. See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.


couldn't find any documentation to resolve it. Through my own efforts, I managed to find a solution. I updated this repository containing the code. Could you please integrate this repository into your program? If everything works without any issues, I intend to publish it to pub.dev.

**Comment by bybabek** [comment]
> > It seems occur when app window was hide, and the app in tray mode
> 
> > [ERROR:flutter/shell/common/shell.cc(1038)] The 'windows_notification' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel. See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
> 
> couldn't find any documentation to resolve it. Through my own efforts, I managed to find a solution. I updated this repository containing the code. Could you please integrate this repository into your program? If everything works without any issues, I intend to publish it to pub.dev.

Yes, the problem is solved. I am not getting that warning message anymore. Thank you
