### ISSUE TITLE
[help wanted]How to register notification to windows settings.

### ISSUE THREAD

**Issue by heiha100** [MohsenHaydari/flutter_windows_notification#19]
I discovered that an application utilizing flutter_windows_notification does not appear in the Windows Notification Manager in the settings. Are there additional steps required to address this issue? The situation can be observed in the following image:
<img width="1075" alt="image" src="https://github.com/mrtnetwork/flutter_windows_notification/assets/134051067/97867271-3f3d-400c-af7e-b649794214b2">

**Comment by mrtnetwork** [comment]
i haven't check this before but I think for Microsoft package MSIX you should config like [this](https://github.com/YehudaKremer/msix/blob/main/doc/toast_notifications_configuration.md)

**Comment by heiha100** [comment]
> i haven't check this before but I think for Microsoft package MSIX you should config like [this](https://github.com/YehudaKremer/msix/blob/main/doc/toast_notifications_configuration.md)

Thanks, I've finally figured out the issue. For Windows, the application needs to create a shortcut in the "Start Menu" and register an AppUserModelID. Once that's done, the problem disappears. That is mentioned in [windows-10-setting-notifications-actions-application-list-is-not-showing-al](https://superuser.com/questions/1782581/windows-10-setting-notifications-actions-application-list-is-not-showing-al).
