### ISSUE TITLE
Push Notifications from Azure

### ISSUE THREAD

**Issue by cliftonlabrum** [MohsenHaydari/flutter_windows_notification#2]
Does this package handle only local notifications? Or can it also display remote notifications sent from a Microsoft Azure notification hub?

I'm trying to figure out how to display remote notifications in my Windows Flutter app. 🤔

**Comment by kiaxseventh** [comment]
dear @mrtnetwork 
please answer this question

**Comment by manandharsudhir** [comment]
@cliftonlabrum did you get any solution for remote push notification for windows app ?

**Comment by cliftonlabrum** [comment]
No, unfortunately not.
