### ISSUE TITLE
Custom Notification Sounds for Windows Toasts

### ISSUE THREAD

**Issue by Rongix** [MohsenHaydari/flutter_windows_notification#20]
# Feature Request: Custom Notification Sounds

### Description:
Currently, flutter_windows_notification's Windows toasts does not support custom notification sounds. This feature request is to add support for custom notification sounds to enhance user experience and provide more customization options for developers.

### Feature Details:

Allow developers to specify custom sound files for notifications displayed using the package.
Support for various sound file formats commonly used for notification sounds (e.g., .wav, .mp3).
Provide a parameter or method within the package API to set the custom notification sound when displaying a toast notification.
#### Use Case:
As an app developer, I want to be able to customize the notification sounds for my Flutter app running on Windows. By providing support for custom notification sounds, I can enhance the branding and user experience of my application.

##### Example Usage:

```
NotificationMessage message = NotificationMessage.fromPluginTemplate(
      "test1",
      "TEXT",
      "TEXT",
      largeImage: file_path,
      image: file_path
      sound: sound_path, // NEW
);
```

### Additional Information:
Custom notification sounds are a common feature in many applications across different platforms. Adding support for custom notification sounds would align with the goal of providing developers with comprehensive tools for building rich and customizable user experiences.

Please check out these resources for more insights about the implementation
https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts

Thank you for considering this feature request.

**Comment by mrtnetwork** [comment]
> # Feature Request: Custom Notification Sounds
> ### Description:
> Currently, flutter_windows_notification's Windows toasts does not support custom notification sounds. This feature request is to add support for custom notification sounds to enhance user experience and provide more customization options for developers.
> 
> ### Feature Details:
> Allow developers to specify custom sound files for notifications displayed using the package. Support for various sound file formats commonly used for notification sounds (e.g., .wav, .mp3). Provide a parameter or method within the package API to set the custom notification sound when displaying a toast notification.
> 
> #### Use Case:
> As an app developer, I want to be able to customize the notification sounds for my Flutter app running on Windows. By providing support for custom notification sounds, I can enhance the branding and user experience of my application.
> 
> ##### Example Usage:
> ```
> NotificationMessage message = NotificationMessage.fromPluginTemplate(
>       "test1",
>       "TEXT",
>       "TEXT",
>       largeImage: file_path,
>       image: file_path
>       sound: sound_path, // NEW
> );
> ```
> 
> ### Additional Information:
> Custom notification sounds are a common feature in many applications across different platforms. Adding support for custom notification sounds would align with the goal of providing developers with comprehensive tools for building rich and customizable user experiences.
> 
> Please check out these resources for more insights about the implementation https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts
> 
> Thank you for considering this feature request.

hi,I will probably add this to the plugin for the plugin templates in the future. It might be possible to add it to the custom template. Have you try it?>

**Comment by mrtnetwork** [comment]
> # Feature Request: Custom Notification Sounds
> ### Description:
> Currently, flutter_windows_notification's Windows toasts does not support custom notification sounds. This feature request is to add support for custom notification sounds to enhance user experience and provide more customization options for developers.
> 
> ### Feature Details:
> Allow developers to specify custom sound files for notifications displayed using the package. Support for various sound file formats commonly used for notification sounds (e.g., .wav, .mp3). Provide a parameter or method within the package API to set the custom notification sound when displaying a toast notification.
> 
> #### Use Case:
> As an app developer, I want to be able to customize the notification sounds for my Flutter app running on Windows. By providing support for custom notification sounds, I can enhance the branding and user experience of my application.
> 
> ##### Example Usage:
> ```
> NotificationMessage message = NotificationMessage.fromPluginTemplate(
>       "test1",
>       "TEXT",
>       "TEXT",
>       largeImage: file_path,
>       image: file_path
>       sound: sound_path, // NEW
> );
> ```
> 
> ### Additional Information:
> Custom notification sounds are a common feature in many applications across different platforms. Adding support for custom notification sounds would align with the goal of providing developers with comprehensive tools for building rich and customizable user experiences.
> 
> Please check out these resources for more insights about the implementation https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts
> 
> Thank you for considering this feature request.

check this and let me know 
https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=xml

`<toast>
    <visual>
        <binding template='ToastGeneric'>
            <text>Notification text.</text>
        </binding>
    </visual>
    <audio src='ms-appx:///Audio/NotificationSound.mp3'/>
</toast>`

**Comment by Rongix** [comment]
Thank you for the detailed solution. It works just as you've explained
