### ISSUE TITLE
10 unresolved externals error

### ISSUE THREAD

**Issue by aditya113141** [MohsenHaydari/flutter_windows_notification#3]
I get the following error when trying to add  `windows_notification: ^0.0.3` in my pubspec.yaml file:- 

"""

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_GetRestrictedErrorInfo referenced in function "public: __cdecl winrt::hresult_error::hresult_error(struct winrt::hresult,struct winrt::take_ownership_from_abi_t)" (??0hresult_error@winrt@@QEAA@Uhresult@1@Utake_ownership_from_abi_t@1@@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_RoGetActivationFactory referenced in function "struct winrt::Windows::Foundation::IActivationFactory __cdecl winrt::get_activation_factory<struct winrt::Windows::Foundation::IActivationFactory>(struct winrt::param::hstring const &)" (??$get_activation_factory@UIActivationFactory@Foundation@Windows@winrt@@@winrt@@YA?AUIActivationFactory@Foundation@Windows@0@AEBUhstring@param@0@@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]    

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_RoOriginateLanguageException referenced in function "private: void __cdecl winrt::hresult_error::originate(struct winrt::hresult,void *)" (?originate@hresult_error@winrt@@AEAAXUhresult@2@PEAX@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_SetRestrictedErrorInfo referenced in function "public: struct winrt::hresult __cdecl winrt::hresult_error::to_abi(void)const " (?to_abi@hresult_error@winrt@@QEBA?AUhresult@2@XZ) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsCreateStringReference referenced in function "public: __cdecl winrt::param::hstring::hstring(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> > const &)" (??0hstring@param@winrt@@QEAA@AEBV?$basic_string_view@_WU?$char_traits@_W@std@@@std@@@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsDeleteString referenced in function "public: static void __cdecl winrt::impl::hstring_traits::close(void *)" (?close@hstring_traits@impl@winrt@@SAXPEAX@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]
windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsPreallocateStringBuffer referenced in function "public: __cdecl winrt::impl::hstring_builder::hstring_builder(unsigned int)" (??0hstring_builder@impl@winrt@@QEAA@I@Z) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsDeleteStringBuffer referenced in function "public: __cdecl winrt::impl::hstring_builder::~hstring_builder(void)" (??1hstring_builder@impl@winrt@@QEAA@XZ) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsPromoteStringBuffer referenced in function "public: struct winrt::hstring __cdecl winrt::impl::hstring_builder::to_hstring(void)" (?to_hstring@hstring_builder@impl@winrt@@QEAA?AUhstring@3@XZ) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

windows_notification_plugin.obj : error LNK2019: unresolved external symbol WINRT_WindowsGetStringRawBuffer referenced in function "public: __cdecl winrt::hstring::operator class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >(void)const " (??Bhstring@winrt@@QEBA?AV?$basic_string_view@_WU?$char_traits@_W@std@@@std@@XZ) [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

tableproject\build\windows\plugins\windows_notification\Debug\windows_notification_plugin.dll : fatal error LNK1120: 10 unresolved externals [tableproject\build\windows\plugins\windows_notification\windows_notification_plugin.vcxproj]

"""

I tried running my application using `flutter run` and got the above error in my terminal.

**Comment by mrtnetwork** [comment]
i think problem is your compiler, please check it https://github.com/flutter/flutter/issues/85880

**Comment by aditya113141** [comment]
Hey, I looked at the example code here - https://github.com/MohsenHaydari/flutter_windows_notification/tree/main/example 

Can you tell what actions did you take to achieve the changes in [Update generated_plugin_registrant.cc](https://github.com/MohsenHaydari/flutter_windows_notification/commit/d11888eca28586d8f9ad40d296c1f92fc6e9d95e) commit

**Comment by mrtnetwork** [comment]
> Hey, I looked at the example code here - https://github.com/MohsenHaydari/flutter_windows_notification/tree/main/example
> 
> Can you tell what actions did you take to achieve the changes in [Update generated_plugin_registrant.cc](https://github.com/MohsenHaydari/flutter_windows_notification/commit/d11888eca28586d8f9ad40d296c1f92fc6e9d95e) commit

In debug mode I try to check something with another plugin like WindowManagerPlugin and SystemTrayPlugin and then I forget to remove the plugin from the dependency and I published it on github, finally I realized and removed the plugin and re-uploaded the item :)

**Comment by aditya113141** [comment]
> > Hey, I looked at the example code here - https://github.com/MohsenHaydari/flutter_windows_notification/tree/main/example
> > Can you tell what actions did you take to achieve the changes in [Update generated_plugin_registrant.cc](https://github.com/MohsenHaydari/flutter_windows_notification/commit/d11888eca28586d8f9ad40d296c1f92fc6e9d95e) commit
> 
> In debug mode I try to check something with another plugin like WindowManagerPlugin and SystemTrayPlugin and then I forget to remove the plugin from the dependency and I published it on github, finally I realized and removed the plugin and re-uploaded the item :)

Okay, I thought it has something to do with my error.
