### ISSUE TITLE
Windows Powersheel x86

### ISSUE THREAD

**Issue by GalangPratamaS** [MohsenHaydari/flutter_windows_notification#4]
In my case, i have installed windows 11.
the notification just showing as windows powersheel x86
![image](https://github.com/MohsenHaydari/flutter_windows_notification/assets/37589128/adb01b0d-dd2a-45a4-8789-3f7bfc8afb34)

**Comment by mrtnetwork** [comment]
u must select your app application id
// application id must be null in packaged mode
`final _winNotifyPlugin = WindowsNotification(applicationId: "r"{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}\WindowsPowerShell\v1.0\powershell.exe"");
`
u can use ```Get-StartApps``` in windows powershell to get your application id and replace with application id
