### ISSUE TITLE
I want open imageURL

### ISSUE THREAD

**Issue by work-ethanhuh** [MohsenHaydari/flutter_windows_notification#5]
Image does not open when imageurl is entered in the image option. 

Is it not possible to open it?

**Comment by mrtnetwork** [comment]
> Image does not open when imageurl is entered in the image option.
> 
> Is it not possible to open it?

hi, no, you must write image bytes to the file, and then use the file path for the image option

**Comment by work-ethanhuh** [comment]
> > Image does not open when imageurl is entered in the image option.
> > Is it not possible to open it?
> 
> hi, no, you must write image bytes to the file, and then use the file path for the image option

It seems to be passing the xml full text as a template, but it seems to be a problem in parsing the xml full text. Is there any way to write the full text of xml as it is?

**Comment by mrtnetwork** [comment]
> > > Image does not open when imageurl is entered in the image option.
> > > Is it not possible to open it?
> > 
> > 
> > hi, no, you must write image bytes to the file, and then use the file path for the image option
> 
> It seems to be passing the xml full text as a template, but it seems to be a problem in parsing the xml full text. Is there any way to write the full text of xml as it is?

https://github.com/MohsenHaydari/flutter_windows_notification/blob/main/lib/windows_notification_method_channel.dart

if you take a look at these codes, I use some pattern like ```#1#``` to replace what I want, when I wrote this package I checked many xml like that and I don't see any problem, I suggest you use some XML editor like the android studio to create XML, then add your pattern to XML and when you want to post notification replace the pattern with anything you want like(big text,text,image,type and etc...)

**Comment by work-ethanhuh** [comment]
> if you take a look at these codes, I use some pattern like `#1#` to replace what I want, when I wrote this package I checked many xml like that and I don't see any problem, I suggest you use some XML editor like the android studio to create XML, then add your pattern to XML and when you want to post notification replace the pattern with anything you want like(big text,text,image,type and etc...)

Then, if there is no problem, putting the imageurl in the template xml should work, isn't it normal?

**Comment by mrtnetwork** [comment]
I just tested with local image path and i don't know about http, or https url

> > if you take a look at these codes, I use some pattern like `#1#` to replace what I want, when I wrote this package I checked many xml like that and I don't see any problem, I suggest you use some XML editor like the android studio to create XML, then add your pattern to XML and when you want to post notification replace the pattern with anything you want like(big text,text,image,type and etc...)
> 
> Then, if there is no problem, putting the imageurl in the template xml should work, isn't it normal?

**Comment by work-ethanhuh** [comment]
> I just tested with local image path and i don't know about http, or https url
> 
> > > if you take a look at these codes, I use some pattern like `#1#` to replace what I want, when I wrote this package I checked many xml like that and I don't see any problem, I suggest you use some XML editor like the android studio to create XML, then add your pattern to XML and when you want to post notification replace the pattern with anything you want like(big text,text,image,type and etc...)
> > 
> > 
> > Then, if there is no problem, putting the imageurl in the template xml should work, isn't it normal?

okaay....got it. Thank you for the quick reply. Have a nice day!
