### ISSUE TITLE
initNotificationCallBack not return arguments

### ISSUE THREAD

**Issue by work-ethanhuh** [MohsenHaydari/flutter_windows_notification#6]
just return null

when using template
in action tag -> imageurl. it is not display image

**Comment by mrtnetwork** [comment]
> just return null
> 
> when using template in action tag -> imageurl. it is not display image

I will try to check and update soon

**Comment by mrtnetwork** [comment]
> just return null
> 
> when using template in action tag -> imageurl. it is not display image

I couldn't find any problems with the image display, but the plugin has been updated, and several tutorials have been added for displaying images. If you encounter any bugs or issues, please let me know.
