### ISSUE TITLE
Close notification call initNotificationCallBack

### ISSUE THREAD

**Issue by thyb-zytek** [MohsenHaydari/flutter_windows_notification#7]
When I close the notification in the Windows notifications center, it calls the initNotificationCallBack method. 

I use the default template.

**Comment by mrtnetwork** [comment]
I've added all types of [events](https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastdismissalreason?view=winrt-22621) in the latest update. Please let me know if there are any problems or bugs
