### ISSUE TITLE
error on compile in dev

### ISSUE THREAD

**Issue by VSP7** [MohsenHaydari/flutter_windows_notification#9]
"C:\1\myapp\windows\flutter\ephemeral\.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: "std::string winrt::to_string(std::wstring_view)": ���������� �८�ࠧ����� ��㬥�� 1 �� "winrt::com_ptr<To>" � "std::wstring_view" [C:\1\myapp\build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj]
Exception: Build process failed."

**Comment by mrtnetwork** [comment]
> "C:\1\myapp\windows\flutter\ephemeral.plugin_symlinks\windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: "std::string winrt::to_string(std::wstring_view)": ���������� �८�ࠧ����� ��㬥�� 1 �� "winrt::com_ptr" � "std::wstring_view" [C:\1\myapp\build\windows\x64\plugins\windows_notification\windows_notification_plugin.vcxproj] Exception: Build process failed."

I don't encounter any issues with compilation on my system. Please ensure you are using the latest version of Flutter for Windows, and verify your development environment. If the problem persists, feel free to ask for further assistance.

**Comment by gmgm60** [comment]
i get the same error
using flutter last version  3.16.5
windows_notification\windows\windows_notification_plugin.cpp(275,32): error C2664: 'std::string winrt::to_string(std::wstring_view)': cannot convert argument 1 from 'winrt::com_ptr<To>' to 'std::wstring_view'
